# Lab Assignment 1

In [2]:
import numpy as np
import torch

## Tensors with numpy and pytorch

In [3]:
print("NumPy Tensors :")
# 1D NumPy
np_1d = np.array([1, 2, 3, 4])
print("NumPy 1D Array:", np_1d)
print("Shape:", np_1d.shape)

# 2D NumPy
np_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nNumPy 2D Array:", np_2d)
print("Shape:", np_2d.shape)

# 3D NumPy
numpy_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nNumPy 3D Array:", numpy_3d)
print("Shape:", numpy_3d.shape)

print("\nPytorch Tensors:")
# 1D PyTorch
torch_1d = torch.tensor([1, 2, 3, 4])
print("PyTorch 1D Tensor:", torch_1d)
print("Shape:", torch_1d.shape)

# 2D PyTorch
torch_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\nPyTorch 2D Tensor:", torch_2d)
print("Shape:", torch_2d.shape)

# 3D PyTorch
torch_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nPyTorch 3D Tensor:", torch_3d)
print("Shape:", torch_3d.shape)


NumPy Tensors :
NumPy 1D Array: [1 2 3 4]
Shape: (4,)

NumPy 2D Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

NumPy 3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)

Pytorch Tensors:
PyTorch 1D Tensor: tensor([1, 2, 3, 4])
Shape: torch.Size([4])

PyTorch 2D Tensor: tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

PyTorch 3D Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


## Basic Operations : Element-wise addition, subtraction, multiplication and division

In [4]:
print("NumPy Element-wise Operations")
# 1D NumPy Operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("\nNumPy 1D Arrays:a=", a,"\nb=", b)
print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (a / b):", a / b)

# 2D NumPy Operations
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
print("\nNumPy 2D Arrays:\n a=", c, "\nb=", d)
print("Addition (c + d):\n", c + d)
print("Subtraction (c - d):\n", c - d)
print("Multiplication (c * d):\n", c * d)
print("Division (c / d):\n", c / d)

print("\n--- PyTorch Element-wise Operations ---")
# 1D PyTorch Operations
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
print("\nPyTorch 1D Tensors:x=", x,"\ny=", y)
print("Addition (x + y):", x + y)
print("Subtraction (x - y):", x - y)
print("Multiplication (x * y):", x * y)
print("Division (x / y):", x / y)

# 2D PyTorch Operations
p = torch.tensor([[1, 2], [3, 4]])
q = torch.tensor([[5, 6], [7, 8]])
print("\nPyTorch 2D Tensors:\np=", p, "\nq=", q)
print("Addition (p + q):\n", p + q)
print("Subtraction (p - q):\n", p - q)
print("Multiplication (p * q):\n", p * q)
print("Division (p / q):\n", p / q)


NumPy Element-wise Operations

NumPy 1D Arrays:a= [1 2 3 4] 
b= [5 6 7 8]
Addition (a + b): [ 6  8 10 12]
Subtraction (a - b): [-4 -4 -4 -4]
Multiplication (a * b): [ 5 12 21 32]
Division (a / b): [0.2        0.33333333 0.42857143 0.5       ]

NumPy 2D Arrays:
 a= [[1 2]
 [3 4]] 
b= [[5 6]
 [7 8]]
Addition (c + d):
 [[ 6  8]
 [10 12]]
Subtraction (c - d):
 [[-4 -4]
 [-4 -4]]
Multiplication (c * d):
 [[ 5 12]
 [21 32]]
Division (c / d):
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

--- PyTorch Element-wise Operations ---

PyTorch 1D Tensors:x= tensor([1, 2, 3, 4]) 
y= tensor([5, 6, 7, 8])
Addition (x + y): tensor([ 6,  8, 10, 12])
Subtraction (x - y): tensor([-4, -4, -4, -4])
Multiplication (x * y): tensor([ 5, 12, 21, 32])
Division (x / y): tensor([0.2000, 0.3333, 0.4286, 0.5000])

PyTorch 2D Tensors:
p= tensor([[1, 2],
        [3, 4]]) 
q= tensor([[5, 6],
        [7, 8]])
Addition (p + q):
 tensor([[ 6,  8],
        [10, 12]])
Subtraction (p - q):
 tensor([[-4, -4],
        [-4

## Dot product and matrix multiplication

In [5]:
a=np.array([[1,2],[4,5]])
b=np.array([[2,4],[3,9]])
print("Matrix 1:\n",a,"\nMatrix 2:\n",b)
matrix_mul=np.matmul(a,b)
x=np.array([1,2,3])
y=np.array([3,-1,0])
print("Vector 1:",x,"\nVector 2:",y)
dotProd=np.dot(x,y)

print("Matrix multiplication of a and b:\n",matrix_mul)
print("Dot product of x and y:",dotProd)

Matrix 1:
 [[1 2]
 [4 5]] 
Matrix 2:
 [[2 4]
 [3 9]]
Vector 1: [1 2 3] 
Vector 2: [ 3 -1  0]
Matrix multiplication of a and b:
 [[ 8 22]
 [23 61]]
Dot product of x and y: 1


## Indexing and Slicing examples :
Boolean masking and extracting subtensor



In [6]:
print("NumPy Indexing and Slicing ")
# 1D NumPy Array
numpy_array_1d = np.array([10, 20, 30, 40, 50])
print("Original 1D NumPy Array:", numpy_array_1d)
print("Element at index 2:", numpy_array_1d[2])
print("Slice from index 1 to 3 (exclusive):", numpy_array_1d[1:4])
print("Every second element:", numpy_array_1d[::2])

# 2D NumPy Array
numpy_array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D NumPy Array:\n", numpy_array_2d)
print("Element at row 1, column 2:", numpy_array_2d[1, 2])
print("First row:", numpy_array_2d[0, :])
print("Second column:", numpy_array_2d[:, 1])
print("Sub-array (first 2 rows, first 2 columns):\n", numpy_array_2d[0:2, 0:2])

print("\nNumPy Boolean Masking")
# 1D Boolean Masking
mask_1d = numpy_array_1d > 25
print("Boolean mask for 1D array (>25):", mask_1d)
print("Elements greater than 25:", numpy_array_1d[mask_1d])

# 2D Boolean Masking
mask_2d = numpy_array_2d % 2 == 0 # Even numbers
print("Boolean mask for 2D array (even numbers):\n", mask_2d)
print("Even numbers in 2D array:", numpy_array_2d[mask_2d])


print("\n--- PyTorch Indexing and Slicing ---")
# 1D PyTorch Tensor
torch_tensor_1d = torch.tensor([10, 20, 30, 40, 50])
print("Original 1D PyTorch Tensor:", torch_tensor_1d)
print("Element at index 2:", torch_tensor_1d[2])
print("Slice from index 1 to 3 (exclusive):", torch_tensor_1d[1:4])
print("Every second element:", torch_tensor_1d[::2])

# 2D PyTorch Tensor
torch_tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D PyTorch Tensor:\n", torch_tensor_2d)
print("Element at row 1, column 2:", torch_tensor_2d[1, 2])
print("First row:", torch_tensor_2d[0, :])
print("Second column:", torch_tensor_2d[:, 1])
print("Sub-tensor (first 2 rows, first 2 columns):\n", torch_tensor_2d[0:2, 0:2])

print("\nPyTorch Boolean Masking")
# 1D Boolean Masking
mask_torch_1d = torch_tensor_1d > 25
print("Boolean mask for 1D tensor (>25):", mask_torch_1d)
print("Elements greater than 25:", torch_tensor_1d[mask_torch_1d])

# 2D Boolean Masking
mask_torch_2d = torch_tensor_2d % 2 == 0 # Even numbers
print("Boolean mask for 2D tensor (even numbers):\n", mask_torch_2d)
print("Even numbers in 2D tensor:", torch_tensor_2d[mask_torch_2d])


NumPy Indexing and Slicing 
Original 1D NumPy Array: [10 20 30 40 50]
Element at index 2: 30
Slice from index 1 to 3 (exclusive): [20 30 40]
Every second element: [10 30 50]

Original 2D NumPy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Sub-array (first 2 rows, first 2 columns):
 [[1 2]
 [4 5]]

NumPy Boolean Masking
Boolean mask for 1D array (>25): [False False  True  True  True]
Elements greater than 25: [30 40 50]
Boolean mask for 2D array (even numbers):
 [[False  True False]
 [ True False  True]
 [False  True False]]
Even numbers in 2D array: [2 4 6 8]

--- PyTorch Indexing and Slicing ---
Original 1D PyTorch Tensor: tensor([10, 20, 30, 40, 50])
Element at index 2: tensor(30)
Slice from index 1 to 3 (exclusive): tensor([20, 30, 40])
Every second element: tensor([10, 30, 50])

Original 2D PyTorch Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Element at row 1, column 2: tensor(6)
First row: tensor([

## .view(), .reshape(), .unsqueeze(), .squeeze() functions in pytorch

In [7]:
print("PyTorch Tensor Shape Manipulation")

# Original 2D tensor
original_tensor = torch.arange(1, 10).reshape(3, 3)
print("Original Tensor:\n", original_tensor)
print("Original Shape:", original_tensor.shape)

viewed_tensor = original_tensor.view(1, 9) # Reshape to 1 row, 9 columns
print("\nTensor after .view(1, 9):\n", viewed_tensor)
print("Shape after .view(1, 9):", viewed_tensor.shape)

viewed_tensor_inferred = original_tensor.view(-1)
print("Tensor after .view(-1) (flattened):", viewed_tensor_inferred)
print("Shape after .view(-1):", viewed_tensor_inferred.shape)


reshaped_tensor = original_tensor.reshape(9, 1)
print("\nTensor after .reshape(9, 1):\n", reshaped_tensor)
print("Shape after .reshape(9, 1):", reshaped_tensor.shape)


single_dim_tensor = torch.tensor([1, 2, 3]) # Shape (3,)
print("\nOriginal 1D Tensor for unsqueeze:", single_dim_tensor)
print("Shape:", single_dim_tensor.shape)

unsqueeze_0 = single_dim_tensor.unsqueeze(0) # Add a dimension at position 0
print("Tensor after .unsqueeze(0):", unsqueeze_0)
print("Shape after .unsqueeze(0):", unsqueeze_0.shape)

unsqueeze_1 = single_dim_tensor.unsqueeze(1) # Add a dimension at position 1
print("Tensor after .unsqueeze(1):\n", unsqueeze_1)
print("Shape after .unsqueeze(1):", unsqueeze_1.shape)

squeezable_tensor = torch.zeros(1, 10, 1, 5, 1) # Shape (1, 10, 1, 5, 1)
print("\nOriginal Squeezable Tensor shape:", squeezable_tensor.shape)

squeezed_tensor = squeezable_tensor.squeeze() # Removes all dimensions of size 1
print("Tensor after .squeeze():", squeezed_tensor.shape)

squeezed_dim_0 = squeezable_tensor.squeeze(0) # Remove dimension at position 0 only if size is 1
print("Tensor after .squeeze(0):", squeezed_dim_0.shape)

squeezed_dim_2 = squeezable_tensor.squeeze(2) # Remove dimension at position 2 only if size is 1
print("Tensor after .squeeze(2):", squeezed_dim_2.shape)

# Squeeze will not remove a dimension if its size is greater than 1
no_change_squeeze = torch.zeros(2, 3, 4)
print("\nOriginal no_change_squeeze shape:", no_change_squeeze.shape)
print("Tensor after .squeeze() on (2,3,4):", no_change_squeeze.squeeze().shape)


PyTorch Tensor Shape Manipulation
Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Original Shape: torch.Size([3, 3])

Tensor after .view(1, 9):
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Shape after .view(1, 9): torch.Size([1, 9])
Tensor after .view(-1) (flattened): tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape after .view(-1): torch.Size([9])

Tensor after .reshape(9, 1):
 tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Shape after .reshape(9, 1): torch.Size([9, 1])

Original 1D Tensor for unsqueeze: tensor([1, 2, 3])
Shape: torch.Size([3])
Tensor after .unsqueeze(0): tensor([[1, 2, 3]])
Shape after .unsqueeze(0): torch.Size([1, 3])
Tensor after .unsqueeze(1):
 tensor([[1],
        [2],
        [3]])
Shape after .unsqueeze(1): torch.Size([3, 1])

Original Squeezable Tensor shape: torch.Size([1, 10, 1, 5, 1])
Tensor after .squeeze(): torch.Size([10, 5])
Tensor after .squeeze(0): torch.Size([10, 1,

## Comparison of reshape function in pytorch and numpy

In [15]:
import time

# Define a large array/tensor size for comparison
size = (1000, 1000)

# NumPy Reshape
numpy_array = np.random.rand(*size)

start_time = time.time()
reshaped_numpy = numpy_array.reshape(1, 1000000)
end_time = time.time()
numpy_time = end_time - start_time
print(f"NumPy reshape time: {numpy_time:.6f} seconds")

# PyTorch Reshape
torch_tensor = torch.randn(*size)

start_time = time.time()
reshaped_torch = torch_tensor.reshape(1, 1000000)
end_time = time.time()
torch_time = end_time - start_time
print(f"PyTorch reshape time: {torch_time:.6f} seconds")

print("\nComparison:")
if numpy_time < torch_time:
    print(f"NumPy reshape was faster by {torch_time - numpy_time:.6f} seconds.")
elif torch_time < numpy_time:
    print(f"PyTorch reshape was faster by {numpy_time - torch_time:.6f} seconds.")
else:
    print("Both reshape operations took approximately the same amount of time.")

NumPy reshape time: 0.000642 seconds
PyTorch reshape time: 0.000222 seconds

Comparison:
PyTorch reshape was faster by 0.000420 seconds.


##

## Broadcasting in PyTorch

Broadcasting in PyTorch (and NumPy) allows arithmetic operations between tensors of different shapes, provided that they are compatible. Two dimensions are compatible when:

1. They are equal, or
2. One of them is 1.

When performing an operation, PyTorch stretches the smaller tensor along the singleton dimensions (dimensions of size 1) to match the larger tensor's shape. This avoids the need to explicitly create larger copies of the smaller tensor, which is memory-efficient and speeds up computations. The elements are virtually copied to perform the operation. If dimensions are incompatible, PyTorch will raise a runtime error.

In [ ]:
print("PyTorch Broadcasting Example")

# Example 1: Scalar broadcasting
a = torch.tensor([1, 2, 3])
b = torch.tensor(10) # Scalar
print(f"\nTensor a: {a}, Shape: {a.shape}")
print(f"Scalar b: {b}, Shape: {b.shape}")
print(f"a + b (scalar broadcasting): {a + b}")

# Example 2: 1D tensor broadcasting to a 2D tensor
c = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
d = torch.tensor([10, 20, 30]) # Shape (3,)

print(f"\nTensor c:\n{c}, Shape: {c.shape}")
print(f"Tensor d: {d}, Shape: {d.shape}")
print(f"c + d (1D to 2D broadcasting):\n{c + d}")

# Example 3: Different dimensions, compatible shapes
e = torch.tensor([[1, 2, 3]]) # Shape (1, 3)
f = torch.tensor([[10], [20]]) # Shape (2, 1)

print(f"\nTensor e:\n{e}, Shape: {e.shape}")
print(f"Tensor f:\n{f}, Shape: {f.shape}")
print(f"e + f (different dimensions, compatible shapes):\n{e + f}")



## In-place and Out-of-place Operations in PyTorch

In PyTorch, operations can be categorized as either **in-place** or **out-of-place**.

### Out-of-place Operations

Most PyTorch operations are out-of-place by default. This means they return a *new* tensor with the result of the operation, leaving the original tensor unchanged. For example, `a + b` creates a new tensor to store the sum of `a` and `b`.

- **Characteristics:**
    - They do not modify the original tensor(s).
    - They return a new tensor containing the result.
    - They might consume more memory because a new tensor is allocated.
    - They are generally safer as they prevent unintended side effects on the original data.

### In-place Operations

In-place operations modify the tensor they are called on directly, without creating a new tensor. In PyTorch, in-place operations are usually denoted by a trailing underscore (`_`) in their method names (e.g., `add_`, `mul_`, `copy_`).

- **Characteristics:**
    - They modify the tensor directly, saving memory by not allocating a new tensor.
    - They typically return `self` (the modified tensor).
    - They can lead to unexpected behavior if not used carefully, especially in computational graphs where gradients are involved (as they break the computational history).
    - Examples include `tensor.add_(other_tensor)`, `tensor.mul_(scalar)`, `tensor.zero_()`.

### Why use in-place operations?

In-place operations are primarily used for:

1.  **Memory Efficiency:** When dealing with very large tensors, creating new tensors for every operation can be memory-intensive. In-place operations can help reduce memory footprint.
2.  **Performance:** Sometimes, in-place operations can offer a slight performance advantage by avoiding new memory allocations and data copying.

### Caution with In-place Operations in Deep Learning

When building neural networks with PyTorch, be careful with in-place operations, especially within `torch.autograd` (PyTorch's automatic differentiation engine). In-place operations can cause issues if the original value of the tensor is needed for gradient computation but has been overwritten. PyTorch's autograd system typically expects operations to be out-of-place to correctly track the computational graph. If an in-place operation modifies a tensor that is an input to an operation for which gradients need to be computed, PyTorch might raise an error or produce incorrect gradients.

In [ ]:
import torch

print("--- Out-of-place Operations ---")
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([4, 5, 6], dtype=torch.float32)
print(f"Original x: {x}")
print(f"Original y: {y}")

# Out-of-place addition
z = x + y
print(f"Result of x + y (new tensor z): {z}")
print(f"x after out-of-place operation: {x} (unchanged)")

# Out-of-place multiplication
a = torch.tensor([10, 20, 30], dtype=torch.float32)
b = a * 2
print(f"\nOriginal a: {a}")
print(f"Result of a * 2 (new tensor b): {b}")
print(f"a after out-of-place operation: {a} (unchanged)")

print("\n--- In-place Operations ---")
p = torch.tensor([1, 2, 3], dtype=torch.float32)
q = torch.tensor([4, 5, 6], dtype=torch.float32)
print(f"Original p: {p}")
print(f"Original q: {q}")

# In-place addition (p.add_(q) is equivalent to p += q)
p.add_(q)
print(f"p after in-place add_ (p += q): {p} (modified)")
print(f"q after in-place add_: {q} (unchanged)")

# Another in-place operation: multiplication with a scalar
r = torch.tensor([10, 20, 30], dtype=torch.float32)
print(f"\nOriginal r: {r}")
r.mul_(2)
print(f"r after in-place mul_ (r *= 2): {r} (modified)")

# In-place zeroing
s = torch.tensor([100, 200, 300], dtype=torch.float32)
print(f"\nOriginal s: {s}")
s.zero_()
print(f"s after in-place zero_(): {s} (modified)")
